### ISSUE TITLE
422 error is not handled in axios other wise great coding

### ISSUE THREAD

**Issue by kumarbets** [jiheon788/react-query-realworld#2]
422 error issue happens, if wrong token is sent and the api response is 422

**Comment by kumarbets** [comment]
422 error gives the below screen. It is caught and promise is rejected. but still getting the below..

![image](https://github.com/user-attachments/assets/6d2f5bdd-f9d3-4f0c-bbea-24baca72654e)

**Comment by kumarbets** [comment]
The above can be fixed , by clearing wrong token in axios error handling. That is simple. However the below error is critical and functionality based. It is just happening because of uselocation

**Comment by kumarbets** [comment]
In your demo site, go to global feed, select any other user, go to their "my articles" - sfsg. Once next page clicked, the profile name becomes null and get into infinite loop. Can you pls help to fix ? Thanks and apprciate

**Comment by jiheon788** [comment]
> The above can be fixed , by clearing wrong token in axios error handling. That is simple. However the below error is critical and functionality based. It is just happening because of uselocation

Thank you for your careful confirmation :)
You're right, there was a fatal error in Pagination, and I'll fix it.

@kumarbets
